import Head from 'next/head'
import HomeComponent from '../components/HomeComponent/HomeComponent'

export default function Home() {
  return (
    <div>
      <Head>
        <title>as</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeComponent />
      </main>

    </div>
  )
}
